POST http://localhost:3001/api/tasks
Content-Type: application/json

{
    "task": "test taskii",
    "description": "test description",
    "priority": 3,
    "completed": false,
    "subTasks": [
        {
            "task": "test subTask",
            "completed": false
        },
        {
            "task": "test subTask2",
            "completed": false
        }
    ],
    "user": "67d05d2f4acbe6352642636a"
}